steps:
- id: 'download models'
  name: 'python:3.8-slim'
  dir: 'server/testdata'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install requests && python download_models.py'
- id: 'get mobilenet'
  name: 'gcr.io/cloud-builders/wget'
  dir: 'server/testdata'
  args: ['--no-check-certificate', 'https://raw.githubusercontent.com/opencv/opencv_extra/master/testdata/dnn/ssd_mobilenet_v2_coco_2018_03_29.pbtxt']
# TODO: solve to permission settings
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'server'
  args: ['app', 'deploy', 'app.yaml']
- id: 'Install npm packages'
  name: 'node:12.9-buster'
  dir: 'front'
  args: ['npm', 'install']
- id: 'Build App'
  name: 'node:12.9-buster'
  dir: 'front'
  args: ['npm', 'run', 'build']
- id: "Deploy to Firebase"
  name: 'gcr.io/$PROJECT_ID/firebase'
  dir: 'front'
  args: ['deploy']
