runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT server:app -t 320

runtime_config:
  python_version: 3.9

handlers:
  - url: /.*
    script: auto

# liveness_check:
#   check_interval_sec: 100
# readiness_check:
#   check_interval_sec: 100
manual_scaling:
  instances: 1

env_variables:
  FLASK_APP: $PWD/server.py
